services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    environment:
      - CANDIDATE_ID=uday.jhariyaa@gmail.com
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GEMINI_MODEL=gemini-3.1-flash-lite
      - DATABASE_URL=sqlite:///./data/local_dev.db
      - FRONTEND_ORIGIN=*
    volumes:
      - ./backend/data:/app/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
